apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccpwgl2
  labels:
    app: ccpwgl2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccpwgl2
  template:
    metadata:
      labels:
        app: ccpwgl2
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: php
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8000
